stages:
  - build
  - test
  - documentation

variables:
  CMAKE_VERSION: "v3.16.0"

.install_vcpkg_dep: &install_vcpkg_dep
  before_script:
    - apt update
    - apt install -y curl zip unzip tar pkg-config cmake # install vcpkg dependencies

.install_latex_dep: &install_latex_dep
  before_script:
    - apt update
    - apt-get install -y texlive-base texlive-latex-recommended texlive-latex-extra

.install_ninja_build: &install_ninja_build
  before_script:
    - apt update
    - apt install -y ninja-build

.install_cmake_3_16_0: &install_cmake_3_16_0
  before_script:
    - apt update
    - apt install -y git
    - mkdir -p /tmp && cd /tmp
    - test -d /tmp/CMake && echo "Found Cached CMake Directory at [/tmp/CMake]" || git clone --depth 1 --branch "$CMAKE_VERSION" https://github.com/Kitware/CMake.git
    - cd ./CMake && ./bootstrap --parallel=$(nproc) > /dev/null 2>&1
    - make -j$(nproc) > /dev/null 2>&1 && make install > /dev/null 2>&1

.testing_default: &testing_default
  before_script:
    - !reference [ .install_vcpkg_dep, before_script ]
    - !reference [ .install_ninja_build, before_script ]
    - !reference [ .install_cmake_3_16_0, before_script ]

.compile_default: &compile_default
  before_script:
    - !reference [ .install_vcpkg_dep, before_script ]
    - !reference [ .install_cmake_3_16_0, before_script ]

.documentation_default: &documentation_default
  before_script:
    - !reference [ .install_vcpkg_dep, before_script ]
    - !reference [ .install_latex_dep, before_script ]
    - !reference [ .install_ninja_build, before_script ]
    - !reference [ .install_cmake_3_16_0, before_script ]

build_gcc_10_3_ninja_debug:
  <<: *compile_default
  stage: build
  image: gcc:10.3
  tags:
    - docker
  script:
    - apt update
    - cd $CI_PROJECT_DIR
    - apt-get install -y ninja-build # install ninja
    - cmake . -B./build/ -DCMAKE_BUILD_TYPE=Release -G Ninja && cd ./build && ninja -j$(nproc) mycc
  cache:
    - key: "gcc_10_3_cmake_$CMAKE_VERSION($CI_RUNNER_ID)"
      paths:
        - "/tmp/CMake"
    - key: "gcc_10_3_ninja_debug_$CI_COMMIT_REF_SLUG($CI_RUNNER_ID)"
      paths:
        - "$CI_PROJECT_DIR/build"

test_gcc_10_3_debug:
  <<: *testing_default
  image: gcc:10.3
  stage: test
  tags:
    - docker
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B./build/ -DCMAKE_BUILD_TYPE=Debug -G Ninja && cd ./build && ninja -j$(nproc) mycc_test
    - cd ./Source && ./mycc_test --gtest_output="xml:gtest_report.xml"
  artifacts:
    when: always
    reports:
      junit: ./build/Source/gtest_report.xml
  needs:
    - build_gcc_10_3_ninja_debug
  cache:
    - key: "gcc_10_3_cmake_$CMAKE_VERSION($CI_RUNNER_ID)"
      paths:
        - "/tmp/CMake"
    - key: "gcc_10_3_ninja_debug_$CI_COMMIT_REF_SLUG($CI_RUNNER_ID)"
      paths:
        - "$CI_PROJECT_DIR/build"

test_gcc_10_3_release:
  <<: *testing_default
  image: gcc:10.3
  stage: test
  tags:
    - docker
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B./build/ -DCMAKE_BUILD_TYPE=Release -G Ninja && cd ./build && ninja -j$(nproc) mycc_test
    - cd ./Source && ./mycc_test --gtest_output="xml:gtest_report.xml"
  artifacts:
    when: always
    reports:
      junit: ./build/Source/gtest_report.xml
  needs:
    - build_gcc_10_3_ninja_debug
  cache:
    - key: "gcc_10_3_cmake_$CMAKE_VERSION($CI_RUNNER_ID)"
      paths:
        - "/tmp/CMake"
    - key: "gcc_10_3_ninja_debug_$CI_COMMIT_REF_SLUG($CI_RUNNER_ID)"
      paths:
        - "$CI_PROJECT_DIR/build"

build_latex_documentation:
  <<: *documentation_default
  image: gcc:10.3
  stage: documentation
  tags:
    - docker
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B./build/ -DCMAKE_BUILD_TYPE=Release -G Ninja && cd ./build && ninja -j$(nproc) documentation
  cache:
    - key: "gcc_10_3_cmake_$CMAKE_VERSION($CI_RUNNER_ID)"
      paths:
        - "/tmp/CMake"