stages:
  - build
  - test

.install_vcpkg_dep: &install_vcpkg_dep
  before_script:
    - apt update
    - apt install -y curl zip unzip tar pkg-config cmake # install vcpkg dependencies

.install_latex_dep: &install_latex_dep
  before_script:
    - apt update
    - apt-get install -y texlive-base texlive-latex-recommended texlive-latex-extra

.install_cmake_3_16_0: &install_cmake_3_16_0
  before_script:
    - apt update
    - apt install -y git
    - mkdir -p /tmp && cd /tmp
    - git clone --depth 1 --branch "v3.16.0" https://github.com/Kitware/CMake.git
    - cd ./CMake && ./bootstrap --parallel=$(nproc) > /dev/null 2>&1
    - make -j$(nproc) > /dev/null 2>&1 && make install > /dev/null 2>&1

.testing_default: &testing_default
  script:
    - !reference [.install_vcpkg_dep, before_script]
    - !reference [.install_cmake_3_16_0, before_script]
    - apt update
    - apt-get install -y ninja-build # install ninja

.compile_default: &compile_default
  before_script:
    - !reference [.install_vcpkg_dep, before_script]
    - !reference [.install_cmake_3_16_0, before_script]

.documentation_default: &documentation_default
  before_script:
    - !reference [.compile_default, before_script]
    - !reference [.install_latex_dep, before_script]

build_gcc_10_3_make_release:
  <<: *compile_default
  stage: build
  image: gcc:10.3
  tags:
    - docker
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B./build/ -DCMAKE_BUILD_TYPE=Release -G 'Unix Makefiles' && cd ./build && make mycc -j$(nproc)

build_gcc_10_3_ninja_release:
  <<: *compile_default
  stage: build
  image: gcc:10.3
  tags:
    - docker
  script:
    - apt update
    - cd ${CI_PROJECT_DIR}
    - apt-get install -y ninja-build # install ninja
    - cmake . -B./build/ -DCMAKE_BUILD_TYPE=Release -G Ninja && cd ./build && make mycc -j$(nproc)

test_gcc_10_3_debug:
  <<: *testing_default
  image: gcc:10.3
  stage: test
  tags:
    - docker
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B./build/ -DCMAKE_BUILD_TYPE=Debug -G Ninja && cd ./build && make mycc_test -j$(nproc)
    - cd ./build/Source && ./mycc_test --gtest_output="xml:gtest_report.xml"
  artifacts:
    when: always
      reports:
        junit: ./build/Source/gtest_report.xml

test_gcc_10_3_release:
  <<: *testing_default
  image: gcc:10.3
  stage: test
  tags:
    - docker
  script:
    - cd $CI_PROJECT_DIR
    - cmake . -B./build/ -DCMAKE_BUILD_TYPE=Release -G Ninja && cd ./build && make mycc_test -j$(nproc)
    - cd ./build/Source && ./mycc_test --gtest_output="xml:gtest_report.xml"
  artifacts:
    when: always
    reports:
      junit: ./build/Source/gtest_report.xml