repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: '^test\/.+$'
      - id: trailing-whitespace
        exclude: '^test\/.+$'
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        exclude: '(^test\/.+)|(.+\.java$)|(.+\.json$)$'
